[package]
name = "blake3-bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib","cdylib"]

[dependencies]
blake3 = "1.3.1"

[build-dependencies]
cbindgen = "0.24.3"
blake3 = "1.3.1"
