[package]
name = "blake3-bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib","cdylib"]

[dependencies]
blake3 = {version = "1.3.1", features=["rayon"]}

[build-dependencies]
cbindgen = "0.24.3"
